//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class episode
    {
        public episode()
        {
            this.episodesToSeasons = new HashSet<episodesToSeason>();
        }
    
        public int episodeID { get; set; }
        public string episodeName { get; set; }
    
        public virtual ICollection<episodesToSeason> episodesToSeasons { get; set; }
    }
}
