//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventType
    {
        public eventType()
        {
            this.events = new HashSet<projectEvent>();
        }
    
        public int eventTypeID { get; set; }
        public string eventTypeName { get; set; }
    
        public virtual ICollection<projectEvent> events { get; set; }
    }
}
