//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class genre
    {
        public genre()
        {
            this.genresToProjects = new HashSet<genresToProject>();
        }
    
        public int genreID { get; set; }
        public string genreName { get; set; }
    
        public virtual ICollection<genresToProject> genresToProjects { get; set; }
    }
}
