//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.collections = new HashSet<collection>();
        }
    
        public int ItemsId { get; set; }
        public Nullable<int> authorID { get; set; }
        public string slug { get; set; }
        public Nullable<int> itemType { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public string title { get; set; }
        public string thumbnail { get; set; }
        public Nullable<int> projectID { get; set; }
    
        public virtual ICollection<collection> collections { get; set; }
        public virtual project project { get; set; }
    }
}
