//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobListing
    {
        public int jobListingID { get; set; }
        public int orderID { get; set; }
        public string realEmail { get; set; }
        public string anonEmail { get; set; }
    
        public virtual order order { get; set; }
    }
}
