//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.jobListings = new HashSet<jobListing>();
        }
    
        public int orderID { get; set; }
        public int userID { get; set; }
        public int productID { get; set; }
        public System.DateTime orderDate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<bool> autoRenew { get; set; }
    
        public virtual ICollection<jobListing> jobListings { get; set; }
        public virtual product product { get; set; }
    }
}
