//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class peopleRole
    {
        public peopleRole()
        {
            this.peopleToCompanies = new HashSet<peopleToCompany>();
            this.peopleToProjects = new HashSet<peopleToProject>();
        }
    
        public int roleID { get; set; }
        public string roleTitle { get; set; }
    
        public virtual ICollection<peopleToCompany> peopleToCompanies { get; set; }
        public virtual ICollection<peopleToProject> peopleToProjects { get; set; }
    }
}
