//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class peopleToProject
    {
        public int personID { get; set; }
        public int projectID { get; set; }
        public int roleID { get; set; }
        public string contractNote { get; set; }
    
        public virtual person person { get; set; }
        public virtual peopleRole peopleRole { get; set; }
        public virtual project project { get; set; }
    }
}
