//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.peopleToProjects = new HashSet<peopleToProject>();
            this.quantitativeDataToPeoples = new HashSet<quantitativeDataToPeople>();
            this.socialSearches = new HashSet<socialSearch>();
        }
    
        public int personID { get; set; }
        public string name { get; set; }
        public Nullable<int> primaryRoleID { get; set; }
        public string archivalTBLink { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthplace { get; set; }
        public string networth { get; set; }
        public string personalNotes { get; set; }
        public string internalNotes { get; set; }
        public string awardNotes { get; set; }
    
        public virtual peopleToCompany peopleToCompany { get; set; }
        public virtual ICollection<peopleToProject> peopleToProjects { get; set; }
        public virtual ICollection<quantitativeDataToPeople> quantitativeDataToPeoples { get; set; }
        public virtual ICollection<socialSearch> socialSearches { get; set; }
    }
}
