//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public project()
        {
            this.items = new HashSet<item>();
            this.eventsToProjects = new HashSet<eventsToProject>();
            this.genresToProjects = new HashSet<genresToProject>();
            this.peopleToProjects = new HashSet<peopleToProject>();
            this.tagsToProjects = new HashSet<tagsToProject>();
            this.socialSearches = new HashSet<socialSearch>();
            this.webLinks = new HashSet<webLink>();
        }
    
        public int projectID { get; set; }
        public string projectName { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<int> ratingID { get; set; }
        public Nullable<System.DateTime> recordCreatedDate { get; set; }
        public Nullable<System.DateTime> recordUpdatedDate { get; set; }
        public string runtime { get; set; }
        public string logLine { get; set; }
        public string synopsis { get; set; }
        public string rottenTomatoesID { get; set; }
        public string imdbID { get; set; }
        public string metaCriticID { get; set; }
        public string productionNotes { get; set; }
        public string locationNotes { get; set; }
        public string distributionNotes { get; set; }
        public string awardNotes { get; set; }
        public string technicalNotes { get; set; }
    
        public virtual ICollection<item> items { get; set; }
        public virtual ICollection<eventsToProject> eventsToProjects { get; set; }
        public virtual ICollection<genresToProject> genresToProjects { get; set; }
        public virtual ICollection<peopleToProject> peopleToProjects { get; set; }
        public virtual rating rating { get; set; }
        public virtual status status { get; set; }
        public virtual ICollection<tagsToProject> tagsToProjects { get; set; }
        public virtual ICollection<socialSearch> socialSearches { get; set; }
        public virtual ICollection<webLink> webLinks { get; set; }
    }
}
