//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectEvent
    {
        public projectEvent()
        {
            this.eventsToProjects = new HashSet<eventsToProject>();
        }
    
        public int eventID { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public string eventName { get; set; }
        public Nullable<int> typeID { get; set; }
    
        public virtual eventType eventType { get; set; }
        public virtual ICollection<eventsToProject> eventsToProjects { get; set; }
    }
}
