//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantitativeDataPoint
    {
        public quantitativeDataPoint()
        {
            this.quantitativeDataToPeoples = new HashSet<quantitativeDataToPeople>();
            this.quantitativeDataToProjects = new HashSet<quantitativeDataToProject>();
        }
    
        public int quantitativeDataPointID { get; set; }
        public Nullable<int> dataSetID { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string customDataLabel { get; set; }
        public string dataAnnotation { get; set; }
        public string accordingTo { get; set; }
    
        public virtual dataSet dataSet { get; set; }
        public virtual ICollection<quantitativeDataToPeople> quantitativeDataToPeoples { get; set; }
        public virtual ICollection<quantitativeDataToProject> quantitativeDataToProjects { get; set; }
    }
}
