//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class quantitativeDataToPeople
    {
        public int quantitativeDataPointID { get; set; }
        public int personID { get; set; }
        public string listPriority { get; set; }
        public Nullable<bool> hidden { get; set; }
    
        public virtual person person { get; set; }
        public virtual quantitativeDataPoint quantitativeDataPoint { get; set; }
    }
}
