//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.projects = new HashSet<project>();
        }
    
        public int statusID { get; set; }
        public string statusName { get; set; }
    
        public virtual ICollection<project> projects { get; set; }
    }
}
