//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTB_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class weblinksType
    {
        public weblinksType()
        {
            this.webLinks = new HashSet<webLink>();
        }
    
        public int typeID { get; set; }
        public string typeName { get; set; }
        public string icon { get; set; }
    
        public virtual ICollection<webLink> webLinks { get; set; }
    }
}
